apiVersion: v1
kind: Namespace
metadata:
  name: frontend
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
spec: {}
status: {}
