apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database
  namespace: database
