apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: k8s-workload-security
featureGates:
  "AppArmor": true
nodes:
- role: control-plane
  image: kindest/node:v1.23.12
  labels: 
    node-type: master
    tier: admin
  # kubeadmConfigPatches:
  #   - |
  #     kind: JoinConfiguration
  #     nodeRegistration:
  #       kubeletExtraArgs:
  #         seccomp-default: "true"
  extraMounts:
  - hostPath: "/home/edinio/GITHUB/k8s-workload-security/kind-cluster/seccomp/"
    containerPath: "/var/lib/kubelet/seccomp/profiles"
  - hostPath: "/home/edinio/GITHUB/k8s-workload-security/kind-cluster/apparmor/"
    containerPath: "/etc/apparmor/profiles"
- role: worker
  image: kindest/node:v1.23.12
  labels: 
    node-type: worker
    tier: frontend
  # kubeadmConfigPatches:
  #   - |
  #     kind: JoinConfiguration
  #     nodeRegistration:
  #       kubeletExtraArgs:
  #         seccomp-default: "true"
  extraMounts:
  - hostPath: "/home/edinio/GITHUB/k8s-workload-security/kind-cluster/seccomp/"
    containerPath: "/var/lib/kubelet/seccomp/profiles"
  - hostPath: "/home/edinio/GITHUB/k8s-workload-security/kind-cluster/apparmor/"
    containerPath: "/etc/apparmor/profiles"
- role: worker
  image: kindest/node:v1.23.12
  labels: 
    node-type: worker
    tier: backend
  # kubeadmConfigPatches:
  #   - |
  #     kind: JoinConfiguration
  #     nodeRegistration:
  #       kubeletExtraArgs:
  #         seccomp-default: "true"
  extraMounts:
  - hostPath: "/home/edinio/GITHUB/k8s-workload-security/kind-cluster/seccomp/"
    containerPath: "/var/lib/kubelet/seccomp/profiles"
  - hostPath: "/home/edinio/GITHUB/k8s-workload-security/kind-cluster/apparmor/"
    containerPath: "/etc/apparmor/profiles"
- role: worker
  image: kindest/node:v1.23.12
  labels: 
    node-type: worker
    tier: database
  # kubeadmConfigPatches:
  #   - |
  #     kind: JoinConfiguration
  #     nodeRegistration:
  #       kubeletExtraArgs:
  #         seccomp-default: "true"
  extraMounts:
  - hostPath: "/home/edinio/GITHUB/k8s-workload-security/kind-cluster/seccomp/"
    containerPath: "/var/lib/kubelet/seccomp/profiles"
  - hostPath: "/home/edinio/GITHUB/k8s-workload-security/kind-cluster/apparmor/"
    containerPath: "/etc/apparmor/profiles"