kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8s-workload-security
nodes:
- role: control-plane
  image: kindest/node:v1.26.2
  labels: 
    node-type: master
    tier: admin
- role: worker
  image: kindest/node:v1.26.2
  labels: 
    node-type: worker
    tier: frontend
- role: worker
  image: kindest/node:v1.26.2
  labels: 
    node-type: worker
    tier: backend
- role: worker
  image: kindest/node:v1.26.2
  labels: 
    node-type: worker
    tier: database
